### PR TITLE
Version resolver -- sort of.

### PR DESCRIPTION
**Pull request by Ormira**
For now I've just added naive version conflict support.
Dependance version resolution is still to implement.

### CODE REVIEW

**Comment by hakan42** [comment]
Ormira, what is the status of this PR? Could you test it with some real-life data?

**Comment by Ormira** [comment]
Conflict detection based on version is working but, as the dependency resolution does not, ckan could resolve a depend/suggest to a version wich is not compatible with the package we are trying to install and throw an error wich can be confusing for the user.

I've started to implement version aware dependency, but didn't had much time since the begining of the year.

**Comment by hakan42** [comment]
Let me tag it as "in progress" then, and let's merge it as and when you deem this be as well-tested...

Mod installation being our core business, I'm always a bit paranoid with changes in the core :smile:

**Comment by AlexanderDzhoganov** [comment]
Closing this as there hasn't been progress for quite a while.

**Pull request closed without merging**
