### PR TITLE
Enable install of incompatible mods, and set KspVersion to return string "Any" when version is null.

### PR DESCRIPTION
**Pull request by ElimGarak**
Hi, long time user, first time submitter.  Please review.  

Made a couple of minor changes.  Purpose:

   - Changed KspVersion to support GUI changes that adds target KSP version to the UI.
   - Changed relationship resolver calls that let the user install mods targeted to a different version.  GUI will pop up a dialog asking the user whether he really wants to install an incompatible version.

### CODE REVIEW

**Comment by Dazpoet** [comment]
Can't say anything about the code but maybe something about the issue of installing incompatible mods.

My knee-jerk reaction is that I don't like the general idea of installing incompatible mods since it would go against the consistency that CKAN values so highly. What is the point of having such a vast metadata repository is if we just let users ignore it, because users will ignore it and do whatever they want if given the chance.

How can we ensure that people don't break their installs if we allow installation of incompatible mods? I'm pretty sure we all click right past GUI warnings in various scenarios on a daily basis without spending much time thinking about them, at least I know I do.

I can see how this would be useful though, just looking at the firespitter situation we've had since 1.0 came out where a perfectly fine (functionwise) mod had to be set to incompatible due to a errormessage which made people think it didn't work. Powerusers quickly figured out that it wasn't a problem but the average user not so much.

From a purely personal perspective though I'd love to be able to force CKAN to install stuff, however I generally solve the few cases I find through hacked .ckan files so the functionallity is kinda available if you're ready to work for it.

Quick sidenote, I understand this change would not affect the CLI-client? If added I would like to see it added to that one aswell.

**Comment by ElimGarak** [comment]
> What is the point of having such a vast metadata repository is if we just let users ignore it, because users will ignore it and do whatever they want if given the chance.

I see what you mean, but personally I view it as giving the users more power over their own install.  For me CKAN has been a way to discover mods, easily install them, and to keep them up to date.

How about I add a change that also turns any incompatible mod red and bold in the mod list?  We can also make the warning before installation of each mod more obnoxious.

> How can we ensure that people don't break their installs if we allow installation of incompatible mods?

Hmm...  That is an issue, but as you said, the other side of the question is also true.  How do we allow users to install mods that are still compatible despite the metadata/code not being updated?

> From a purely personal perspective though I'd love to be able to force CKAN to install stuff, however I generally solve the few cases I find through hacked .ckan files so the functionallity is kinda available if you're ready to work for it.

I suspect that the majority of people don't even know what the .ckan files are, let alone how to edit them and what to modify in them.  The whole point of the GUI is to make things easier for end user, and this isn't.

> Quick sidenote, I understand this change would not affect the CLI-client? If added I would like to see it added to that one aswell.

What is the CIL-client?  I would be glad to add this functionality to it too.  Is that the command-line interface, that lives in CKAN-cmdline?

**Comment by pjf** [comment]
I'm mostly off the net today because I'm madly working on an android privacy talk I'm presenting tonight, so I'm not going to have a chance to look at all the proposed changes just yet. However it's worth noting a few things about how the CKAN is structured.

The *core* of CKAN, what we compile into `ckan.dll`, exists to implement and enforce the CKAN spec, which in itself is derived from the Debian spec. With our goals of correctness and repeatability, it's the part of the system which I care the most about. If anyone's building a client that uses a different front-end (be that integrated into KSP itself, a Gtk# implementation, an HTML5+JS front-end, or anything else), then it's the core which enforces that everything works the right way. The core needs to do the right thing for all clients, both present and future.

> Hmm... That is an issue, but as you said, the other side of the question is also true. How do we allow users to install mods that are still compatible despite the metadata/code not being updated?

One of the reasons we have KSP versions in our metadata is so we can give the users something we know that will work on their platform. The complaint that "X still works on Y but the metadata says otherwise" is a common one, and it has a *really* good solution, which is to correct the metadata. That solves the problem not just for the individual, but for *everyone*.

So one discussion to have is how do we make it easier for metadata to be updated? The idea of an on-line editor has been raised a number of times, and the `.ckan` and `.netkan` file formats are JSON to make something like this much easier. If mods release with `.version` files in them, then we're already able to pick up on those; likewise we can get version information off releases made on KerbalStuff.

Am I correct what we're aiming for is a way to handle mods that don't come with new releases for new KSP versions, but continue to work regardless?

(And with that, I'm *totally* out of time! Back to my talk-writing!)

**Comment by pjf** [comment]
@ElimGarak: Today I'm [sprinting](https://patreon.com/pjf0) CKAN changes, so I've more of a chance to look at this properly.

So, I can verify the core indeed lets you install incompatible versions. I can do a `ckan.exe upgrade kOS=0.14` on the command-line, and it will happily install an old kOS release. `ckan list` will show that as being out of date, but we can do it just fine (using the `AddRemove` functionality in the core). That's good, because we *should* allow older versions to be installed if they're specifically requested.

Updating `InstallList` to completely disable checking our installed KSP version, however, is not at all a good idea. One of the reasons we have metadata on KSP versions is so the user *can* get the version they need. I'm still playing on 0.90, and I can be very confident that when I install or upgrade a mod, I'll be getting the right one for my system.

I'm totally happy with a CKAN client (which includes the GUI) providing functionality to request incompatible versions to be installed, but in that case it *shouldn't* be calling the default the `InstallList` functionality, which is purely provided for clients which want to "do the typical thing". I have a hunch the GUI is already doing a lot of its own relationship resolution anyway, and it should definitely be using `AddRemove()` (even though I don't believe it is now), once we have a final list of changes to make.

At a glance the version changes look fine, although I want to check if there's anther PR to the GUI that uses these. (If not, can you briefly expand on their rationale?)

Many thanks!

~ Paul

**Comment by pjf** [comment]
I'm clearing PRs today, and while I really don't like to turn down contributions, as this stands I can't merge his in good faith. As mentioned in my previous post, the CKAN core already lets you install incompatible mods, but you must be explicit. This change would have our resolution engine *implicitly* select incompatible mods, which is contrary to our goals.

So, no objections to patching the clients to allow users to explicitly specify mod versions to install (the cmdline already has this), but a definite objection to having the core implicitly install mods we know to be incompatible.

**Pull request closed without merging**
