### PR TITLE
Add curlsharp mutli-downloads to core.

### PR DESCRIPTION
**Pull request by pjf**
Listen up kids, because these downloads are da shiz! They report progress just like the native downloads, they handle all the SSL certificates you want, they have freakin' test cases¹, and they bring great joy and love to everyone on Mac and Linux systems.

These are the result of a 12-hour code sprint, with thanks to everyone on [Patreon](https://patreon.com/pjf0) who supported me. :)

¹ `nunit-console --include=NetAsyncDownloader Tests/bin/Debug/Tests.dll`

### CODE REVIEW

**Comment by hakan42** [comment]
You are AMAZING, Sir! :smile:

**Comment by pjf** [comment]
@hakan42 : As are you! :D 

I should note I've got a [test build](https://dl.dropboxusercontent.com/u/9702672/KSP/ckan-curlsharp.exe) available. I know that jenkins builds the PR into a `.dll`, but after 12 hours of looking at code I'm not yet sure if it builds a whole client. :)

`--verbose` mode also shows a little more about what's going on with the downloads, and `--debug` probably gives too much info. :)

I should also note that the cancel button doesn't seem to work in the GUI, but it doesn't seem to work *without* these changes for me either, so I'm counting that as an existing bug rather than anything caused by my work here. :)

**Comment by Dazpoet** [comment]
This PR should very much link to https://github.com/KSP-CKAN/CKAN-support/issues/107 so we know to close that one when this is merged and stable :+1:

**Comment by techman83** [comment]
libcurl FTW! Looks good, tests pass locally.

**Pull request merged**
