### PR TITLE
Adds in version checking with validation.

### PR DESCRIPTION
**Pull request by Almagnus1**
Adds in defines for new and old version checking.

Also adds in validation.

### CODE REVIEW

**Comment by pjf** [comment]
A few notes on this:

1. Epoch is a sequence that won't be seen in the version number proper; it's prepended so that if version numbers change in a strange way¹, we can simply have a way of rebooting the versioning sequence. As such, we very much want it at the front (eg: 1:[version]), and it should never include non-numeric characters, as it will always be added by our tools, and never by the upstream metadata. I'm about to patch `netkan.exe` to allow epoch insertion very shortly, since it's an easy way to solve backwards numbering (which extends *well* beyond people adding and removing 'v's at the start).
2. Right now the new code isn't active, and both the old and new code are sitting in the same file. There's no real reason to leave the old code in if it's being replaced, and there's no reason to add new code in unless it's activated. Can you update this to just be the new code? That will also mean our CI system will be able to test it properly to look for problems.
3. I'm still catching up on all the discussions, but we'd need very compelling reasons to make client-visible changes to have versions are handled, as this has potential impact on all existing mods that we've indexed (over 2,200 of them), as well as requiring all users to upgrade. I'm not saying the reasons aren't compelling until I catch up onthose discussions, but as previously mentioned, [improvements to the indexing tools](https://github.com/KSP-CKAN/CKAN-support/issues/133#issuecomment-100200855) allows for the same problems to be solved but without the risk of impacting existing metadata, nor any requirement for users to upgrade their clients.

¹ We see this a *lot* around April Fool's.

**Comment by Almagnus1** [comment]
One of the reasons I haven't activated the new code is that it's gonna fail several of the tests.  The rest of this post goes into what's going to fail before activating the code:

Specifically, all the tests in:
void StringComparison 
void NumberComparison

The reason for this is that they test two methods that are:

internal static Comparison StringComp
internal static Comparison NumComp

Using VS's Find All References on each of the method names shows that they only referenced within Version.cs.  Using both of these methods is part of what's slowing down the version comparison, and causing a longer load time as it's causing the string to be parsed several times over during the comparison.

void Complex:
"v6a5" and "v6a12" are odd ways to do version numbering, and the tests makes the assumption that 'a' acts as '.', so they would be similar to 6.5 and 6.12.  One could argue that it's just a hash, so string comparison would be in order.

Everything else is expected to pass.

**Comment by Almagnus1** [comment]
I'm also adjusting AGExt to be a harder test as it was comparing:
1.20
1.22a

And now it's comparing:
1.2b
1.12a

This validates that the substring is being parsed correctly (as 12 > 2), and not doing a simple string compare, as a string compare may yield 2b > 12a, which is wrong.

**Comment by RichardLake** [comment]
Closed. See https://github.com/KSP-CKAN/CKAN/issues/963

**Pull request closed without merging**
